### ISSUE TITLE
Suggestion: replace video with code examples

### ISSUE THREAD

**Issue by hi5** [ahkscript/homepage#15]
https://autohotkey.com/boards/viewtopic.php?p=130435#p130435

Some examples from other languages:

* https://www.python.org/
* https://www.ruby-lang.org/en/
* https://nim-lang.org/
* and no doubt many more 😸

**Comment by joedf** [comment]
Agreed. I need some code samples...
What should be covered?

**Comment by hi5** [comment]
Four examples should be good enough - what is already in the example code posted https://autohotkey.com/boards/viewtopic.php?p=130435#p130435 

1. Hotstrings & Hotkeys 
2. Clipboard example
3. Short GUI
4. Simple Array (to show we have objects etc) ⬅️ to be added

**Comment by joedf** [comment]
Alright-y, I'll have all of them integrated when i have time. I think I might make it like python's carousel.

**Comment by hi5** [comment]
That is indeed a nice one 👍

**Comment by joedf** [comment]
Had a little bit of free time.
Preview: https://ahkscript.github.io/homepage/codeexamples.html

**Comment by mmikeww** [comment]
all good, but def use monospaced font

**Comment by joedf** [comment]
Yes, sorry. forgot about websafe fonts. I was using DejaVu Mono.
Updated. https://github.com/ahkscript/homepage/blob/gh-pages/assets/monokai.css#L20

**Comment by hi5** [comment]
Perhaps an Array/Object example as 4th

```autohotkey
; AutoHotkey (Associative) Arrays
Colors:="Red,Green,Blue"           ; string
ColorArray:=StrSplit(Colors, ",")  ; create array

ColorArray.Push("Purple")          ; add data

for index, element in ColorArray   ; Read from the array
	MsgBox % "Color " index " = " element

**Comment by joedf** [comment]
Fully intergrated,

**Comment by mmikeww** [comment]
nice, but what about some indentation? :)

**Comment by joedf** [comment]
I just used the code as is :0
The code style is from a SciTE export. The styling is static.

**Comment by hi5** [comment]
Looks nice if I do say so myself :-)

**Comment by joedf** [comment]
Thanks :D

**Comment by ahkon** [comment]
Looks good. :)

A couple small suggestions:
1. The cursor changes to the 'text-select'/ 'I-Bar' style cursor when mousing over the buttons '1', '2', '3', '4'. I think this cursor is not appropriate for a button.

2. The delay (5 seconds) seems a bit fast for trying to read the code in detail. Perhaps increase the length of the delay. OR add a button that toggles play/pause.

**Comment by joedf** [comment]
Updated. 👍

**Comment by ahkon** [comment]
A few more things.

1. It is difficult to highlight and copy the code examples. Could this be made easier?
2. The GUI example does not exit after it has displayed the MsgBox. It seems like that would be the expected behavior.
3. The Clipboard example; should it clear the clipboard first and use ClipWait?

**Comment by joedf** [comment]
You're right. I didn't even think of copying; fixed in new commit.
I won't change the examples unless there's pre-written optimized code presented to me.

**Comment by ahkon** [comment]
Thanks :)
I just wanted to start the discussion regarding GUI/clipboard the examples.

**Comment by joedf** [comment]
No problem ;)
