### ISSUE TITLE
"Learn More" Links

### ISSUE THREAD

**Issue by ahkon** [ahkscript/homepage#19]
Suggest changing the links.

"Key Binds" - I think should point to here: https://autohotkey.com/docs/Hotkeys.htm#Intro

"Is it good for me" - This one I'm the least convinced of, but maybe it should simply be https://autohotkey.com/docs/AutoHotkey.htm

"Why AutoHotkey" - The script showcase is a bit dated. The Awesome AutoHotkey list is supposed to feature scripts that work with the current version of AHK. https://github.com/ahkscript/awesome-AutoHotkey

**Comment by joedf** [comment]
All great suggestions!
