### ISSUE TITLE
Fix (update): PocketPC link (CAB installer no longer available on ahk . net)

### ISSUE THREAD

**Issue by hi5** [ahkscript/homepage#30]
See issue at awesome here https://github.com/ahkscript/awesome-AutoHotkey/issues/157

**Comment by Tallefer** [comment]
Is there a newer version of that CAB? I think I saw something like 1.0.48.8xx on the forums in later posts, but not sure.

**Comment by hi5** [comment]
That I'm not sure about, according to my time/date stamps I saved the files in 2014 but I don't recall where I grabbed them from. The files in the CAB  are dated 16-08-2011. 

The CAB file I found earlier on another site shows 26-10-2010 so that looks like an older version. 

:crossed_fingers:  someone comes along with the sources and/or the last version - hopefully Micha himself :)

**Comment by Tallefer** [comment]
Also there are some more bits on Russian site, maybe anything is still worth getting: https://4pda.ru/forum/index.php?showtopic=197562
The last post in particular, seems like a custom-built compiler with additional FileSelectFile/FileSelectFolder functions.

**Comment by joedf** [comment]
@hi5 Great work. I think it's better to have it under ahkscript in case any of us decide to change GitHub habits (change username, delete account, etc.) or what not... And I'll update it the homepage to link to it. I'll make you'll have admin access to that repo, if something needs to be changed or wtv.

**Comment by joedf** [comment]
Awesome 👍
