### ISSUE TITLE
Forums button: make it not transparent

### ISSUE THREAD

**Issue by hi5** [ahkscript/homepage#4]
Somewhat difficult to read, make is sold white, on hover perhaps white text on blue bg

**Comment by joedf** [comment]
Should not happen now... i think?

**Comment by hi5** [comment]
It remains personal preference, but I prefer solid buttons so I don't see the photo shine through, 
better contrast never hurts 👓 👀 😃

**Comment by ahkon** [comment]
I like the current button color setup :)

**Comment by joedf** [comment]
I agree with both... but it shall remain as it. :p

**Comment by hi5** [comment]
But perhaps make both buttons the same width 📏  ❓

**Comment by joedf** [comment]
I guess... but that's just the automatic/responsive size....

**Comment by ahkon** [comment]
I'm undecided about the button width. It looks OK now...
